# Generated by Django 5.0.3 on 2024-03-26 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
    ]
